Feature/481 party receipt
fecgov/fecfile-validate pull request #125
Opened 2022-10-31 19:16 UTC by mjtravers

2022-10-31 21:00 UTC, toddlees requested changes

2022-10-31 21:00 UTC, toddlees commented on schema/PARTY_RECEIPT.json
> +    "description": "Transfer (12)",
`"description": "Party Receipt (11b)",`

2022-10-31 21:02 UTC, toddlees requested changes

2022-10-31 21:02 UTC, toddlees commented on schema/PARTY_RECEIPT.json
> +        "donor_committee_fec_id"
`"donor_committee_name"`

2022-11-01 16:34 UTC, mjtravers commented on schema/PARTY_RECEIPT.json
> +    "description": "Transfer (12)",
fixed

2022-11-01 16:34 UTC, mjtravers commented on schema/PARTY_RECEIPT.json
> +        "donor_committee_fec_id"
fixed. good catch!

2022-11-01 17:53 UTC, toddlees approved these changes

2022-11-01 18:04 UTC, Elaine-Krauss-TCG approved these changes

2022-11-01 18:37 UTC, merged