Feature/489 unregistered receipt from person
fecgov/fecfile-validate pull request #163
Opened 2023-01-04 19:34 UTC by Elaine-Krauss-TCG

App#489

2023-01-05 13:01 UTC, toddlees approved these changes

2023-01-05 13:01 UTC, toddlees commented on schema/UNREGISTERED_RECEIPT_FROM_PERSON_RETURN.json
> +            "minLength": 1,
Very good catch with minLength: 1

2023-01-05 14:00 UTC, toddlees requested changes
You're right about the cpd label needing to change. Aurelia left a comment pointing out that the label is different from ones where it says "(Optional)".

2023-01-10 19:40 UTC, mjtravers approved these changes

2023-01-10 19:42 UTC, merged