Feature/spec verification
fecgov/fecfile-validate pull request #171
Opened 2023-01-19 17:42 UTC by Elaine-Krauss-TCG

Adds a new python script to the bin that checks for differences between the repo's JSON Schema files and a given spreadsheet.  The default spreadsheet is "spec.xlsx" though the user can specify any .xlsx file they want.

Running the script with the "-v" flag will have it log minor errors (e.g. differences in Sample Data)

2023-01-25 00:03 UTC, mjtravers requested changes
Looks great. Just needs the command line parameters to be managed by argparse and some documentation at the top of the file explaining what the script is used for and how it is used. See inline comments for more details

2023-01-25 16:16 UTC, Elaine-Krauss-TCG commented on bin/verify-spec-files.py
> +                exit()
The script now uses argparse as requested

2023-01-25 16:16 UTC, Elaine-Krauss-TCG commented on bin/verify-spec-files.py
> +
Header documentation has been added in

2023-01-26 18:01 UTC, mjtravers approved these changes

2023-01-26 18:02 UTC, merged