[WIP] Feature/517 earmark hq account
fecgov/fecfile-validate pull request #173
Opened 2023-01-30 15:40 UTC by Elaine-Krauss-TCG

2023-01-30 22:07 UTC, mjtravers requested changes
@Elaine-Krauss-TCG Made comments where changes to the schema can be made. Also, there is an if condition when using "pattern" that is not getting picked up by the script that generates the documentation spec html table. That script should be updated to include that rule. See inline comment for a pointer on how to code that.

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +            ],
since required, should be "type": "string"

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +            ],
since required, should be "type": "string"

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +                "REQUIRED": null,
REQUIRED needs "X (error)"

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +                "REQUIRED": null,
REQUIRED needs "X (error)"

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +                ]
This required is not necessary and can be removed because aggregation_group is already required in the required list at the top of the file

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +                    "aggregation_group"
This required is not necessary and can be removed because aggregation_group is already required in the required list at the top of the file

2023-01-30 22:07 UTC, mjtravers commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +                ]
This required is not necessary and can be removed because aggregation_group is already required in the required list at the top of the file

2023-01-30 23:03 UTC, Elaine-Krauss-TCG commented on schema/NATIONAL_PARTY_EARMARK_RECEIPTS.json
> +                        "pattern": "^Recount/Legal Proceedings Account - Earmarked Through [ -~]{0,46}$",
Looks like I've got it working
![image](https://user-images.githubusercontent.com/104506225/215616265-2160769f-a1a1-4976-b2da-2b4a0314b3b3.png)

2023-01-30 23:13 UTC, Elaine-Krauss-TCG commented on schema/NATIONAL_PARTY_EARMARK_RECEIPTS.json
> +                        "pattern": "^Recount/Legal Proceedings Account - Earmarked Through [ -~]{0,46}$",
Got it working, and it actually got me to recognize that the `contribution_purpose_descrip` in the AllOf for this file actually had a typo in it...

![image](https://user-images.githubusercontent.com/104506225/215617858-791a6709-e5ca-4840-892a-f1ed7d5fb0a3.png)

2023-01-30 23:15 UTC, Elaine-Krauss-TCG commented on schema/NATIONAL_PARTY_EARMARK_MEMOS.json
> +        "memo_code"
:+1:

2023-01-31 22:00 UTC, mjtravers approved these changes

2023-01-31 22:00 UTC, merged