Removes comments from schema tokens
fecgov/fecfile-validate pull request #35
Opened 2022-02-03 20:42 UTC by toddlees

2022-02-03 21:30 UTC, mjtravers requested changes
Don't forget to run the generate-schema-doc for the SchA and copy the HTML output to the /docs directory

2022-02-04 16:41 UTC, toddlees commented
I've reverted the backlog schema, but it's worth noting that running the generate schema docs script without specifying a file results in a SchA.html based on schema/backlog/SchA.json rather than schema/SchA.json, which might be unexpected.

2022-02-04 18:47 UTC, mjtravers requested changes
Found a {} reference in the fec_recommended array. We'll have to be sure to no longer copy files from the backlog directory up to the schema directory now that we're editing the schema files directly.

2022-02-04 18:47 UTC, mjtravers commented on schema/SchA.json
> +        "contribution_amount": {
The property name in the fec_recommended array needs to be removed as well:

    "fec_recommended": [
        "contributor_street_1",
        "contributor_city",
        "contributor_state",
        "contributor_zip",
        "contribution_date",
        "contribution_amount_{f3l_bundled}"
    ],

2022-02-04 21:26 UTC, mjtravers approved these changes
looks good

2022-02-04 21:26 UTC, merged