[WIP] feature/34 npm validator
fecgov/fecfile-validate pull request #55
Opened 2022-03-24 15:37 UTC by rfultz

# Work in Progress

2022-04-04 14:54 UTC, mjtravers commented
The SonarCloud Code Analysis is reporting 0% code coverage for the new javascript code. This is inaccurate as there are unit tests for this code. The issue is that CircleCI is configured to send code coverage reports to SonarCloud for the javascript code as it is for the python code. This ticket has been generated to fix this issue: #60

2022-04-12 13:54 UTC, toddlees requested changes

2022-04-12 13:54 UTC, toddlees commented on fecfile_validate_js/tests/index.test.ts
> +    // TODO: the next line is the goal. Ajv sees '' as a value and we want it to be evaluated as null
why is this the goal? `''` is different from null.  If we configure our schema such that a field is required and the min length is 0, we have approved `''` as a valid entry. I don't believe that we _should_ be allowing `''` but I think that's a matter of setting the `minLength` and or the `pattern` properly.  My reasoning for that is that length is a string property and not a matter of defined or undefined.  `minLenght` and `pattern` are ways that we define string rules.  `required` is how is define whether or not a field must be defined.

2022-04-12 13:54 UTC, toddlees commented on schema/F3X.json
> +            "pattern": "^[A-Z]{2}$",
This is a good improvement on the pattern!

2022-04-12 13:54 UTC, toddlees commented on schema/F3X.json
> +            "pattern": "^[C|P][0-9]{8}$|^[H|S][0-9]{1}[A-Z]{2}[0-9]{5}$",
Super useful definition of committee id

2022-04-12 14:21 UTC, toddlees approved these changes
Approving the package

2022-04-12 14:29 UTC, merged